// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";

export const keys = {
  all: ["billing", "webhooks"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function stripeWebhooks(): Promise<unknown> {
  return platformJson(`/billing/api/v1/webhooks/stripe`, { method: "POST" });
}

export async function appleWebhooks(): Promise<unknown> {
  return platformJson(`/billing/api/v1/webhooks/apple`, { method: "POST" });
}

export async function googleWebhooks(): Promise<unknown> {
  return platformJson(`/billing/api/v1/webhooks/google`, { method: "POST" });
}
