// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";

export const keys = {
  all: ["notifications", "notifications"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyNotification(params?: { "page"?: number; "pageSize"?: number }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/notifications/api/v1/notifications/me?${qs}` : `/notifications/api/v1/notifications/me`;
  return platformJson(url);
}

export async function getMyUnreadCount(): Promise<unknown> {
  return platformJson(`/notifications/api/v1/notifications/me/unread-count`);
}

export async function readNotification(id: string): Promise<unknown> {
  return platformJson(`/notifications/api/v1/notifications/${encodeURIComponent(id)}/read`, { method: "PUT" });
}

export async function updateNotificationsReadAll(): Promise<unknown> {
  return platformJson(`/notifications/api/v1/notifications/read-all`, { method: "PUT" });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
