// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UpdatePreferenceRequest = Schemas["FitnessLink.Module.Notifications.Application.Features.Preferences.DTOs.UpdatePreferenceRequest"];

export const keys = {
  all: ["notifications", "notification-preferences"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyNotificationPreference(): Promise<unknown> {
  return platformJson(`/notifications/api/v1/notification-preferences/me`);
}

export async function updateNotificationPreferencesMe(body: UpdatePreferenceRequest): Promise<unknown> {
  return platformJson(`/notifications/api/v1/notification-preferences/me`, { method: "PUT", body: JSON.stringify(body) });
}
