// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UnlockAchievementRequest = Schemas["FitnessLink.Module.Core.Application.Features.Achievements.DTOs.UnlockAchievementRequest"];

export const keys = {
  all: ["core", "achievements"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listAchievements(): Promise<unknown> {
  return platformJson(`/core/api/v1/achievements`);
}

export async function createAchievement(body: UnlockAchievementRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/achievements`, { method: "POST", body: JSON.stringify(body) });
}

export async function getMyAchievement(): Promise<unknown> {
  return platformJson(`/core/api/v1/achievements/me`);
}
