// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type WorkoutSuggestionRequest = Schemas["FitnessLink.Module.Core.Application.Features.AI.DTOs.WorkoutSuggestionRequest"];
export type AnalyzeSessionRequest = Schemas["FitnessLink.Module.Core.Application.Features.AI.DTOs.AnalyzeSessionRequest"];

export const keys = {
  all: ["core", "ai"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function workoutSuggestionAi(body: WorkoutSuggestionRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/ai/workout-suggestion`, { method: "POST", body: JSON.stringify(body) });
}

export async function analyzeSessionAi(body: AnalyzeSessionRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/ai/analyze-session`, { method: "POST", body: JSON.stringify(body) });
}
