// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UpdateCalendarEntryRequest = Schemas["FitnessLink.Module.Core.Application.Features.Calendar.DTOs.UpdateCalendarEntryRequest"];
export type CreateCalendarEntryRequest = Schemas["FitnessLink.Module.Core.Application.Features.Calendar.DTOs.CreateCalendarEntryRequest"];

export const keys = {
  all: ["core", "calendar"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyCalendar(params?: { "startDate"?: string; "endDate"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/calendar/me?${qs}` : `/core/api/v1/calendar/me`;
  return platformJson(url);
}

export async function getCalendar(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/calendar/${encodeURIComponent(id)}`);
}

export async function updateCalendar(id: string, body: UpdateCalendarEntryRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/calendar/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteCalendar(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/calendar/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function createCalendar(body: CreateCalendarEntryRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/calendar`, { method: "POST", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
