// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";

export const keys = {
  all: ["core", "classification"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listClassificationAnatomy(): Promise<unknown> {
  return platformJson(`/core/api/v1/classification/anatomy`);
}

export async function listClassificationEquipment(): Promise<unknown> {
  return platformJson(`/core/api/v1/classification/equipment`);
}

export async function listClassificationTrainingLevels(): Promise<unknown> {
  return platformJson(`/core/api/v1/classification/training-levels`);
}

export async function listClassificationContentStatuses(): Promise<unknown> {
  return platformJson(`/core/api/v1/classification/content-statuses`);
}

export async function listClassificationRpeScales(): Promise<unknown> {
  return platformJson(`/core/api/v1/classification/rpe-scales`);
}
