// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type ShareContentRequest = Schemas["FitnessLink.Module.Core.Application.Features.Content.DTOs.ShareContentRequest"];

export const keys = {
  all: ["core", "content"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function favoritesContent(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/content/favorites/${encodeURIComponent(id)}`, { method: "POST" });
}

export async function listContentFavorites(): Promise<unknown> {
  return platformJson(`/core/api/v1/content/favorites`);
}

export async function shareContent(body: ShareContentRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/content/share`, { method: "POST", body: JSON.stringify(body) });
}

export async function listContentShared(): Promise<unknown> {
  return platformJson(`/core/api/v1/content/shared`);
}

export async function uploadContent(): Promise<unknown> {
  return platformJson(`/core/api/v1/content/upload`, { method: "POST" });
}
