// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateContributorRequest = Schemas["FitnessLink.Module.Core.Application.Features.Contributors.DTOs.CreateContributorRequest"];
export type BulkReassignRequest = Schemas["FitnessLink.Module.Core.Application.Features.Contributors.DTOs.BulkReassignRequest"];
export type UpdateContributorRequest = Schemas["FitnessLink.Module.Core.Application.Features.Contributors.DTOs.UpdateContributorRequest"];

export const keys = {
  all: ["core", "contributors"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listContributors(params?: { "page"?: number; "pageSize"?: number; "type"?: string; "includeDeleted"?: boolean }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/contributors?${qs}` : `/core/api/v1/contributors`;
  return platformJson(url);
}

export async function createContributor(body: CreateContributorRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/contributors`, { method: "POST", body: JSON.stringify(body) });
}

export async function listContributorsPendingApproval(params?: { "page"?: number; "pageSize"?: number }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/contributors/pending-approval?${qs}` : `/core/api/v1/contributors/pending-approval`;
  return platformJson(url);
}

export async function bulkReassignContributors(body: BulkReassignRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/contributors/bulk-reassign`, { method: "POST", body: JSON.stringify(body) });
}

export async function getContributor(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/contributors/${encodeURIComponent(id)}`);
}

export async function updateContributor(id: string, body: UpdateContributorRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/contributors/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteContributor(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/contributors/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function listContributorContent(id: string, params?: { "page"?: number; "pageSize"?: number }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/contributors/${encodeURIComponent(id)}/content?${qs}` : `/core/api/v1/contributors/${encodeURIComponent(id)}/content`;
  return platformJson(url);
}

export async function approveContributor(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/contributors/${encodeURIComponent(id)}/approve`, { method: "POST" });
}

export async function rejectContributor(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/contributors/${encodeURIComponent(id)}/reject`, { method: "POST" });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
