// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateGoalRequest = Schemas["FitnessLink.Module.Core.Application.Features.Goals.DTOs.CreateGoalRequest"];
export type UpdateGoalRequest = Schemas["FitnessLink.Module.Core.Application.Features.Goals.DTOs.UpdateGoalRequest"];
export type UpdateGoalProgressRequest = Schemas["FitnessLink.Module.Core.Application.Features.Goals.DTOs.UpdateGoalProgressRequest"];

export const keys = {
  all: ["core", "goals"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listGoals(): Promise<unknown> {
  return platformJson(`/core/api/v1/goals`);
}

export async function createGoal(body: CreateGoalRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/goals`, { method: "POST", body: JSON.stringify(body) });
}

export async function getGoal(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/goals/${encodeURIComponent(id)}`);
}

export async function updateGoal(id: string, body: UpdateGoalRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/goals/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteGoal(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/goals/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function progressGoal(id: string, body: UpdateGoalProgressRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/goals/${encodeURIComponent(id)}/progress`, { method: "PUT", body: JSON.stringify(body) });
}
