// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateHabitRequest = Schemas["FitnessLink.Module.Core.Application.Features.Habits.DTOs.CreateHabitRequest"];
export type UpdateHabitRequest = Schemas["FitnessLink.Module.Core.Application.Features.Habits.DTOs.UpdateHabitRequest"];
export type LogHabitRequest = Schemas["FitnessLink.Module.Core.Application.Features.Habits.DTOs.LogHabitRequest"];

export const keys = {
  all: ["core", "habits"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listHabits(): Promise<unknown> {
  return platformJson(`/core/api/v1/habits`);
}

export async function createHabit(body: CreateHabitRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/habits`, { method: "POST", body: JSON.stringify(body) });
}

export async function getMyHabit(): Promise<unknown> {
  return platformJson(`/core/api/v1/habits/me`);
}

export async function getHabitGoal(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/habits/goal/${encodeURIComponent(id)}`);
}

export async function getHabit(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/habits/${encodeURIComponent(id)}`);
}

export async function updateHabit(id: string, body: UpdateHabitRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/habits/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteHabit(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/habits/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function logHabit(id: string, body: LogHabitRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/habits/${encodeURIComponent(id)}/log`, { method: "POST", body: JSON.stringify(body) });
}

export async function listHabitStreak(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/habits/${encodeURIComponent(id)}/streak`);
}
