// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateMeasurementRequest = Schemas["FitnessLink.Module.Core.Application.Features.BodyTracking.DTOs.CreateMeasurementRequest"];
export type UpdateMeasurementRequest = Schemas["FitnessLink.Module.Core.Application.Features.BodyTracking.DTOs.UpdateMeasurementRequest"];

export const keys = {
  all: ["core", "measurements"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyMeasurement(): Promise<unknown> {
  return platformJson(`/core/api/v1/measurements/me`);
}

export async function createMeasurement(body: CreateMeasurementRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/measurements`, { method: "POST", body: JSON.stringify(body) });
}

export async function updateMeasurement(id: string, body: UpdateMeasurementRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/measurements/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteMeasurement(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/measurements/${encodeURIComponent(id)}`, { method: "DELETE" });
}
