// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type ResolveMediaRequest = Schemas["FitnessLink.Module.Core.Application.Features.Media.DTOs.ResolveMediaRequest"];

export const keys = {
  all: ["core", "media"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function resolveMedia(body: ResolveMediaRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/media/resolve`, { method: "POST", body: JSON.stringify(body) });
}

export async function getMyToday(params?: { "utcOffsetMinutes"?: number }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/media/me/today?${qs}` : `/core/api/v1/media/me/today`;
  return platformJson(url);
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
