// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateMilestoneRequest = Schemas["FitnessLink.Module.Core.Application.Features.Milestones.DTOs.CreateMilestoneRequest"];

export const keys = {
  all: ["core", "milestones"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listMilestones(): Promise<unknown> {
  return platformJson(`/core/api/v1/milestones`);
}

export async function createMilestone(body: CreateMilestoneRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/milestones`, { method: "POST", body: JSON.stringify(body) });
}

export async function getMilestoneGoal(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/milestones/goal/${encodeURIComponent(id)}`);
}

export async function achieveMilestone(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/milestones/${encodeURIComponent(id)}/achieve`, { method: "PUT" });
}
