// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateMovementRequest = Schemas["FitnessLink.Module.Core.Application.Features.Movements.DTOs.CreateMovementRequest"];
export type UpdateMovementRequest = Schemas["FitnessLink.Module.Core.Application.Features.Movements.DTOs.UpdateMovementRequest"];
export type PublishContentRequest = Schemas["FitnessLink.Module.Core.Application.Features.ContentPublishing.DTOs.PublishContentRequest"];

export const keys = {
  all: ["core", "movements"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listMovements(params?: { "page"?: number; "pageSize"?: number; "source"?: string; "contributorId"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/movements?${qs}` : `/core/api/v1/movements`;
  return platformJson(url);
}

export async function createMovement(body: CreateMovementRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/movements`, { method: "POST", body: JSON.stringify(body) });
}

export async function listMovementsListView(): Promise<unknown> {
  return platformJson(`/core/api/v1/movements/list-view`);
}

export async function getMovement(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/movements/${encodeURIComponent(id)}`);
}

export async function updateMovement(id: string, body: UpdateMovementRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/movements/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteMovement(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/movements/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function publishMovement(id: string, body: PublishContentRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/movements/${encodeURIComponent(id)}/publish`, { method: "POST", body: JSON.stringify(body) });
}

export async function unpublishMovement(id: string, body: PublishContentRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/movements/${encodeURIComponent(id)}/unpublish`, { method: "POST", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
