// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UpdateOrganizationRequest = Schemas["FitnessLink.Module.Core.Application.Features.Organization.DTOs.UpdateOrganizationRequest"];

export const keys = {
  all: ["core", "organization"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listOrganization(): Promise<unknown> {
  return platformJson(`/core/api/v1/organization`);
}

export async function putOrganization(body: UpdateOrganizationRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/organization`, { method: "PUT", body: JSON.stringify(body) });
}
