// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";

export const keys = {
  all: ["core", "personalization"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listPersonalization(): Promise<unknown> {
  return platformJson(`/core/api/v1/personalization`);
}

export async function getMyPersonalization(): Promise<unknown> {
  return platformJson(`/core/api/v1/personalization/me`);
}

export async function mePersonalization(): Promise<unknown> {
  return platformJson(`/core/api/v1/personalization/me`, { method: "POST" });
}

export async function getPersonalizationUser(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/personalization/user/${encodeURIComponent(id)}`);
}
