// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateProgramRequest = Schemas["FitnessLink.Module.Core.Application.Features.Programs.DTOs.CreateProgramRequest"];
export type UpdateProgramRequest = Schemas["FitnessLink.Module.Core.Application.Features.Programs.DTOs.UpdateProgramRequest"];
export type AddWeeklyWorkoutRequest = Schemas["FitnessLink.Module.Core.Application.Features.Programs.DTOs.AddWeeklyWorkoutRequest"];

export const keys = {
  all: ["core", "programs"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listPrograms(params?: { "page"?: number; "pageSize"?: number }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/programs?${qs}` : `/core/api/v1/programs`;
  return platformJson(url);
}

export async function createProgram(body: CreateProgramRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/programs`, { method: "POST", body: JSON.stringify(body) });
}

export async function listProgramsListView(): Promise<unknown> {
  return platformJson(`/core/api/v1/programs/list-view`);
}

export async function getProgram(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/programs/${encodeURIComponent(id)}`);
}

export async function updateProgram(id: string, body: UpdateProgramRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/programs/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function weeklyWorkoutsProgram(id: string, body: AddWeeklyWorkoutRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/programs/${encodeURIComponent(id)}/weekly-workouts`, { method: "POST", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
