// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateProgressPhotoRequest = Schemas["FitnessLink.Module.Core.Application.Features.BodyTracking.DTOs.CreateProgressPhotoRequest"];

export const keys = {
  all: ["core", "progress-photos"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyProgressPhoto(): Promise<unknown> {
  return platformJson(`/core/api/v1/progress-photos/me`);
}

export async function createProgressPhoto(body: CreateProgressPhotoRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/progress-photos`, { method: "POST", body: JSON.stringify(body) });
}

export async function deleteProgressPhoto(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/progress-photos/${encodeURIComponent(id)}`, { method: "DELETE" });
}
