// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";

export const keys = {
  all: ["core", "reports"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listReportsWorkouts(params?: { "since"?: string; "to"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/reports/workouts?${qs}` : `/core/api/v1/reports/workouts`;
  return platformJson(url);
}

export async function listReportsNutrition(params?: { "since"?: string; "to"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/reports/nutrition?${qs}` : `/core/api/v1/reports/nutrition`;
  return platformJson(url);
}

export async function listReportsAdminOverview(): Promise<unknown> {
  return platformJson(`/core/api/v1/reports/admin-overview`);
}

export async function listReportCustomerAdherence(id: string, params?: { "since"?: string; "until"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/reports/customer/${encodeURIComponent(id)}/adherence?${qs}` : `/core/api/v1/reports/customer/${encodeURIComponent(id)}/adherence`;
  return platformJson(url);
}

export async function listReportContentEngagement(id: string, params?: { "type"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/reports/content/${encodeURIComponent(id)}/engagement?${qs}` : `/core/api/v1/reports/content/${encodeURIComponent(id)}/engagement`;
  return platformJson(url);
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
