// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateRoleRequest = Schemas["FitnessLink.Module.Core.Application.Features.Roles.DTOs.CreateRoleRequest"];
export type UpdateRolePermissionsRequest = Schemas["FitnessLink.Module.Core.Application.Features.Roles.DTOs.UpdateRolePermissionsRequest"];

export const keys = {
  all: ["core", "roles"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listRoles(): Promise<unknown> {
  return platformJson(`/core/api/v1/roles`);
}

export async function createRole(body: CreateRoleRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/roles`, { method: "POST", body: JSON.stringify(body) });
}

export async function listRolePermissions(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/roles/${encodeURIComponent(id)}/permissions`);
}

export async function permissionsRole(id: string, body: UpdateRolePermissionsRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/roles/${encodeURIComponent(id)}/permissions`, { method: "PUT", body: JSON.stringify(body) });
}
