// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type StartSessionRequest = Schemas["FitnessLink.Module.Core.Application.Features.Sessions.DTOs.StartSessionRequest"];
export type CompleteSessionRequest = Schemas["FitnessLink.Module.Core.Application.Features.Sessions.DTOs.CompleteSessionRequest"];
export type LogHistoryRequest = Schemas["FitnessLink.Module.Core.Application.Features.Sessions.DTOs.LogHistoryRequest"];
export type LogBodyDataRequest = Schemas["FitnessLink.Module.Core.Application.Features.Sessions.DTOs.LogBodyDataRequest"];

export const keys = {
  all: ["core", "sessions"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listSessions(): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions`);
}

export async function createSession(body: StartSessionRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions`, { method: "POST", body: JSON.stringify(body) });
}

export async function getSession(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/${encodeURIComponent(id)}`);
}

export async function getMySession(): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/me`);
}

export async function getSessionUser(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/user/${encodeURIComponent(id)}`);
}

export async function completeSession(id: string, body: CompleteSessionRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/${encodeURIComponent(id)}/complete`, { method: "POST", body: JSON.stringify(body) });
}

export async function listSessionHistory(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/${encodeURIComponent(id)}/history`);
}

export async function historySession(id: string, body: LogHistoryRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/${encodeURIComponent(id)}/history`, { method: "POST", body: JSON.stringify(body) });
}

export async function listSessionBodyData(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/${encodeURIComponent(id)}/body-data`);
}

export async function bodyDataSession(id: string, body: LogBodyDataRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/sessions/${encodeURIComponent(id)}/body-data`, { method: "POST", body: JSON.stringify(body) });
}
