// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type AddTaxonomyGroupRequest = Schemas["FitnessLink.Module.Core.Application.Features.Taxonomy.DTOs.AddTaxonomyGroupRequest"];
export type AddTaxonomyTagRequest = Schemas["FitnessLink.Module.Core.Application.Features.Taxonomy.DTOs.AddTaxonomyTagRequest"];

export const keys = {
  all: ["core", "taxonomy"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listTaxonomy(): Promise<unknown> {
  return platformJson(`/core/api/v1/taxonomy`);
}

export async function groupsTaxonomy(body: AddTaxonomyGroupRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/taxonomy/groups`, { method: "POST", body: JSON.stringify(body) });
}

export async function groupsTagsTaxonomy(id: string, body: AddTaxonomyTagRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/taxonomy/groups/${encodeURIComponent(id)}/tags`, { method: "POST", body: JSON.stringify(body) });
}
