// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UpdateUserRequest = Schemas["FitnessLink.Module.Core.Application.Features.Users.DTOs.UpdateUserRequest"];
export type CreateUserRequest = Schemas["FitnessLink.Module.Core.Application.Features.Users.DTOs.CreateUserRequest"];
export type UpdatePreferenceRequest = Schemas["FitnessLink.Module.Core.Application.Features.Users.DTOs.UpdatePreferenceRequest"];

export const keys = {
  all: ["core", "users"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyUser(): Promise<unknown> {
  return platformJson(`/core/api/v1/users/me`);
}

export async function getUser(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/users/${encodeURIComponent(id)}`);
}

export async function updateUser(id: string, body: UpdateUserRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/users/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function createUser(body: CreateUserRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/users`, { method: "POST", body: JSON.stringify(body) });
}

export async function listUserPreferences(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/users/${encodeURIComponent(id)}/preferences`);
}

export async function preferencesUser(id: string, body: UpdatePreferenceRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/users/${encodeURIComponent(id)}/preferences`, { method: "PUT", body: JSON.stringify(body) });
}

export async function meProfilePhotoUsers(): Promise<unknown> {
  return platformJson(`/core/api/v1/users/me/profile-photo`, { method: "POST" });
}
