// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UpdateWeightEntryRequest = Schemas["FitnessLink.Module.Core.Application.Features.BodyTracking.DTOs.UpdateWeightEntryRequest"];
export type CreateWeightEntryRequest = Schemas["FitnessLink.Module.Core.Application.Features.BodyTracking.DTOs.CreateWeightEntryRequest"];

export const keys = {
  all: ["core", "weight"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyWeight(params?: { "since"?: string; "to"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/weight/me?${qs}` : `/core/api/v1/weight/me`;
  return platformJson(url);
}

export async function getWeight(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/weight/${encodeURIComponent(id)}`);
}

export async function updateWeight(id: string, body: UpdateWeightEntryRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/weight/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteWeight(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/weight/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function createWeight(body: CreateWeightEntryRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/weight`, { method: "POST", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
