// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateWorkoutRequest = Schemas["FitnessLink.Module.Core.Application.Features.Workouts.DTOs.CreateWorkoutRequest"];
export type UpdateWorkoutRequest = Schemas["FitnessLink.Module.Core.Application.Features.Workouts.DTOs.UpdateWorkoutRequest"];

export const keys = {
  all: ["core", "workouts"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listWorkouts(params?: { "page"?: number; "pageSize"?: number }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/core/api/v1/workouts?${qs}` : `/core/api/v1/workouts`;
  return platformJson(url);
}

export async function createWorkout(body: CreateWorkoutRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts`, { method: "POST", body: JSON.stringify(body) });
}

export async function listWorkoutsListView(): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts/list-view`);
}

export async function getWorkout(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts/${encodeURIComponent(id)}`);
}

export async function updateWorkout(id: string, body: UpdateWorkoutRequest): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteWorkout(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function getWorkoutContributor(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts/contributor/${encodeURIComponent(id)}`);
}

export async function listWorkoutTasks(id: string): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts/${encodeURIComponent(id)}/tasks`);
}

export async function getWorkoutTask(id: string, taskId: string): Promise<unknown> {
  return platformJson(`/core/api/v1/workouts/${encodeURIComponent(id)}/tasks/${encodeURIComponent(taskId)}`);
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
