// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";

export const keys = {
  all: ["nutrition", "foods"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listFoodsSearch(params?: { "query"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/nutrition/api/v1/foods/search?${qs}` : `/nutrition/api/v1/foods/search`;
  return platformJson(url);
}

export async function getFood(id: string): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/foods/${encodeURIComponent(id)}`);
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
