// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UpdateFoodEntryRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.FoodEntries.DTOs.UpdateFoodEntryRequest"];
export type CreateFoodEntryRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.FoodEntries.DTOs.CreateFoodEntryRequest"];

export const keys = {
  all: ["nutrition", "food-entries"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyFoodEntry(params?: { "date"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/nutrition/api/v1/food-entries/me?${qs}` : `/nutrition/api/v1/food-entries/me`;
  return platformJson(url);
}

export async function getMyAll(params?: { "page"?: number; "pageSize"?: number }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/nutrition/api/v1/food-entries/me/all?${qs}` : `/nutrition/api/v1/food-entries/me/all`;
  return platformJson(url);
}

export async function getFoodEntry(id: string): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/food-entries/${encodeURIComponent(id)}`);
}

export async function updateFoodEntry(id: string, body: UpdateFoodEntryRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/food-entries/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteFoodEntry(id: string): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/food-entries/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function createFoodEntry(body: CreateFoodEntryRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/food-entries`, { method: "POST", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
