// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateGroceryItemRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.Grocery.DTOs.CreateGroceryItemRequest"];

export const keys = {
  all: ["nutrition", "grocery"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyGrocery(): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/grocery/me`);
}

export async function createGrocery(body: CreateGroceryItemRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/grocery`, { method: "POST", body: JSON.stringify(body) });
}

export async function toggleGrocery(id: string): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/grocery/${encodeURIComponent(id)}/toggle`, { method: "PUT" });
}

export async function generateGrocery(): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/grocery/generate`, { method: "POST" });
}

export async function deleteGrocery(id: string): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/grocery/${encodeURIComponent(id)}`, { method: "DELETE" });
}
