// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type UpdateMealSlotRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.MealSlots.DTOs.UpdateMealSlotRequest"];
export type CreateMealSlotRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.MealSlots.DTOs.CreateMealSlotRequest"];

export const keys = {
  all: ["nutrition", "meal-slots"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyMealSlot(params?: { "day"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/nutrition/api/v1/meal-slots/me?${qs}` : `/nutrition/api/v1/meal-slots/me`;
  return platformJson(url);
}

export async function getMealSlot(id: string): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/meal-slots/${encodeURIComponent(id)}`);
}

export async function updateMealSlot(id: string, body: UpdateMealSlotRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/meal-slots/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

export async function deleteMealSlot(id: string): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/meal-slots/${encodeURIComponent(id)}`, { method: "DELETE" });
}

export async function createMealSlot(body: CreateMealSlotRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/meal-slots`, { method: "POST", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
