// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateMealPlanTemplateRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.MealPlanTemplates.DTOs.CreateMealPlanTemplateRequest"];
export type UpdateMealPlanTemplateRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.MealPlanTemplates.DTOs.UpdateMealPlanTemplateRequest"];

export const keys = {
  all: ["nutrition", "meal-plan-templates"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listMealPlanTemplates(params?: { "page"?: number; "pageSize"?: number; "source"?: string; "contributorId"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/nutrition/api/v1/meal-plan-templates?${qs}` : `/nutrition/api/v1/meal-plan-templates`;
  return platformJson(url);
}

export async function createMealPlanTemplate(body: CreateMealPlanTemplateRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/meal-plan-templates`, { method: "POST", body: JSON.stringify(body) });
}

export async function updateMealPlanTemplate(id: string, body: UpdateMealPlanTemplateRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/meal-plan-templates/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
