// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateNutritionGoalRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.NutritionGoals.DTOs.CreateNutritionGoalRequest"];

export const keys = {
  all: ["nutrition", "nutrition-goals"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function getMyNutritionGoal(): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/nutrition-goals/me`);
}

export async function createNutritionGoal(body: CreateNutritionGoalRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/nutrition-goals`, { method: "POST", body: JSON.stringify(body) });
}
