// AUTO-GENERATED by scripts/gen-api-clients.mjs — do not hand-edit.
// Regenerate with `npm run gen:api:clients` after the OpenAPI snapshot changes.

import { platformJson } from "../client";
import type { components } from "@/types/api";

type Schemas = components["schemas"];

export type CreateRecipeRequest = Schemas["FitnessLink.Module.Nutrition.Application.Features.Recipes.DTOs.CreateRecipeRequest"];

export const keys = {
  all: ["nutrition", "recipes"] as const,
  lists: () => [...keys.all, "list"] as const,
  list: (params?: Record<string, unknown>) => [...keys.lists(), params ?? {}] as const,
  details: () => [...keys.all, "detail"] as const,
  detail: (id: string) => [...keys.details(), id] as const,
} as const;

export async function listRecipes(params?: { "page"?: number; "pageSize"?: number; "source"?: string; "contributorId"?: string }): Promise<unknown> {
  const qs = buildQuery(params);
  const url = qs ? `/nutrition/api/v1/recipes?${qs}` : `/nutrition/api/v1/recipes`;
  return platformJson(url);
}

export async function createRecipe(body: CreateRecipeRequest): Promise<unknown> {
  return platformJson(`/nutrition/api/v1/recipes`, { method: "POST", body: JSON.stringify(body) });
}

function buildQuery(params: Record<string, unknown> | undefined): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) q.set(k, String(v));
  }
  return q.toString();
}
